# Generated by Django 4.2.5 on 2023-09-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
